Ritual/Ritual/Areas/Admin/Controllers/DifferentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Ritual.Domain;
using Ritual.Domain.Entities;
using Ritual.Services;

namespace Ritual.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DifferentController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public DifferentController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Different() : dataManager.Dif.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Different model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.Dif.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Dif.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Ritual/Ritual/Controllers/DifferentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ritual.Domain;

namespace Ritual.Controllers
{
    public class DifferentController : Controller
    {
        private readonly DataManager dataManager;

        public DifferentController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.Dif.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageDifferent");
            return View(dataManager.Dif.GetServiceItems());
        }
    }
}

Ritual/Ritual/Views/Different/Index.cshtml
@using Ritual.Domain.Entities
@model IQueryable<Ritual.Domain.Entities.Different>
@section metatags
{
    <title>Купить ритуальные принадлежности в Глубоком</title>
    <meta name="description" content="Продажа ритуальных принадлежностей по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
    @*<meta name="keywords" content="asdasddas" />*@
}

<div>
    <article id="main" class="container special">


        <p>
            МАГАЗИН «РИТУАЛ» НА М.ГОРЬКОГО 32 ПРЕДЛАГАЕТ ВАШЕМУ ВНИМАНИЮ БОЛЬШОЙ ВЫБОР РУШНИКОВ,<br>
            ПОКРЫВАЛ ИСКУСТВЕННЫХ ЦВЕТОВ, РИТУАЛЬНОЙ ОТРЕБУТИКИ И Т.Д
        </p>
    </article>
    @if (Model.Any())
    {
        <section class="carousel">
            <div class="reel">
                @foreach (Different entity in Model)
                {
                    <article>
                        <a asp-area="" asp-controller="Different" asp-action="Index" asp-route-id="@entity.Id"><img src="~/images/@entity.TitleImagePath" alt="" class="imageDif featuredNew"/></a>
                        <header>
                            <h3>@entity.Subtitle</h3>
                        </header>
                    </article>
                }

            </div>
        </section>
    }

</div>

Ritual/Ritual/Views/Different/Show.cshtml
@model Ritual.Domain.Entities.Different
@section metatags
{
    <title>Купить ритуальные принадлежности в Глубоком</title>
    <meta name="description" content="Продажа ритуальных принадлежностей по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
   
}

<div>
    <article id="main" class="container special">

        <img class="image featured" src="~/images/@Model.TitleImagePath" />
        <h2>
            @Model.Title
        </h2>
    </article>
</div>