Ritual/Ritual/Areas/Admin/Controllers/WhreatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Ritual.Domain;
using Ritual.Domain.Entities;
using Ritual.Services;

namespace Ritual.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WhreatController : Controller
    {
    private readonly DataManager dataManager;
    private readonly IWebHostEnvironment hostingEnvironment;
    public WhreatController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
    {
        this.dataManager = dataManager;
        this.hostingEnvironment = hostingEnvironment;
    }

    public IActionResult Edit(Guid id)
    {
        var entity = id == default ? new Wreath() : dataManager.Wreath.GetWreathsId(id);
        return View(entity);
    }
    [HttpPost]
    public IActionResult Edit(Wreath model, IFormFile titleImageFile)
    {
        if (ModelState.IsValid)
        {
            if (titleImageFile != null)
            {
                model.TitleImagePath = titleImageFile.FileName;
                using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                {
                    titleImageFile.CopyTo(stream);
                }
            }
            dataManager.Wreath.SaveWreath(model);
            return RedirectToAction(nameof(HomeController.IndexWhres), nameof(HomeController).CutController());
        }
        return View(model);
    }

    [HttpPost]
    public IActionResult Delete(Guid id)
    {
        dataManager.Wreath.DeleteWreath(id);
        return RedirectToAction(nameof(HomeController.IndexWhres), nameof(HomeController).CutController());
    }
    }
}

Ritual/Ritual/Controllers/WhreatController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ritual.Domain;

namespace Ritual.Controllers
{
    public class WhreatController : Controller
    {
        private readonly DataManager dataManager;

        public WhreatController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.Wreath.GetWreathsId(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageWhreat");
            return View(dataManager.Wreath.getWreaths());
        }
    }
}

Ritual/Ritual/Views/Whreat/Index.cshtml
@using Ritual.Domain.Entities
@model IQueryable<Ritual.Domain.Entities.Wreath>
@section metatags
{
    <title>Купить корзину, венок в Глубоком</title>
    <meta name="description" content="Продажа венков по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
 
}

<div>
    <article id="main" class="container special">
        <p>РИТУАЛЬНЫЕ ВЕНКИ И КОРЗИНЫ ПОМОГУТ ВЫРАЗИТЬ ЭМОЦИИ УТРАТЫ В ТРУДНУЮ МИНУТУ</p>
    </article>
    @if (Model.Any())
    {
        <section class="carousel">
            <div id="whreat" class="reel">
                @foreach (Wreath entity in Model)
                {
                    <article>
                        <a asp-area="" asp-controller="Whreat" asp-action="Index" asp-route-id="@entity.Id">
                            <img src="~/images/@entity.TitleImagePath" alt="" class="imageWhreat featuredNew"/>
                        </a>
                        <header>
                            <h3>@entity.Subtitle</h3>
                        </header>
                    </article>
                }

            </div>
        </section>
    }

</div>

Ritual/Ritual/Views/Whreat/Show.cshtml
@model Ritual.Domain.Entities.Wreath
@section metatags
{
    <title>Купить корзину, венок в Глубоком</title>
    <meta name="description" content="Продажа венков по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />

}
<div>
    <article id="main" class="container special">
        <img class="image featured" src="~/images/@Model.TitleImagePath" />
        <h2>
            @Model.Title
        </h2>
    </article>
</div>