Ritual/Ritual/Areas/Admin/Controllers/CrossController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Ritual.Domain;
using Ritual.Domain.Entities;
using Ritual.Services;

namespace Ritual.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CrossController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        public CrossController(DataManager dataManager, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Cross() : dataManager.Cross.GetServiceItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(Cross model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                dataManager.Cross.SaveServiceItem(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.Cross.DeleteServiceItem(id);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Ritual/Ritual/Controllers/CrossController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ritual.Domain;

namespace Ritual.Controllers
{
    public class CrossController : Controller
    {
        private readonly DataManager dataManager;

        public CrossController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
           
            if (id != default)
            {
                return View("Show", dataManager.Cross.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageCross");
            return View(dataManager.Cross.GetServiceItems());
        }
    }
}

Ritual/Ritual/Views/Cross/Index.cshtml
@using Ritual.Domain.Entities
@model IQueryable<Ritual.Domain.Entities.Cross>
@section metatags
{
    <title>Купить крест в Глубоком</title>
    <meta name="description" content="Продажа крестов по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
    
}
<div>

    <article id="main" class="container special">

        <p>
            Кресты на могилу  относятся к категории ключевой атрибутики.<br>
            Это не просто привычный элемент на могиле, это – уникальный символ вечной жизни.<br>
            Традиционно крест устанавливают сразу после захоронения.
        </p>
    </article>
    @if (Model.Any())
    {
        <section class="carousel">
            <div class="reel">
                @foreach (Cross entity in Model)
                {
                    <article>
                        <a asp-area="" asp-controller="Cross" asp-action="Index" asp-route-id="@entity.Id"><img src="~/images/@entity.TitleImagePath" alt="" class="image featuredNew"/></a>
                        <header>
                            <h3>@entity.Subtitle</h3>
                        </header>
                    </article>
                }

            </div>
        </section>
    }

</div>

Ritual/Ritual/Views/Cross/Show.cshtml
@model Ritual.Domain.Entities.Cross
@section metatags
{
    <title>Купить крест в Глубоком</title>
    <meta name="description" content="Продажа крестов по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
    
}
<div>
    <article id="main" class="container special">
        <img class="image featured" src="~/images/@Model.TitleImagePath" />
        <h2>
            @Model.Title
        </h2>
    </article>
</div>