Ritual/Ritual/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ritual.Domain;

namespace Ritual.Controllers
{
    public class ServicesController : Controller
    {
        private readonly DataManager dataManager;

        public ServicesController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index(Guid id)
        {
            if (id != default)
            {
                return View("Show", dataManager.ServiceItems.GetServiceItemById(id));
            }

            ViewBag.TextField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");
            return View(dataManager.ServiceItems.GetServiceItems());
        }
    }
}

Ritual/Ritual/Views/Services/Index.cshtml
@using Ritual.Domain.Entities
@model IQueryable<Ritual.Domain.Entities.ServiceItem>
@section metatags
{
    <title>Купить гроб в Глубоком</title>
    <meta name="description" content="Продажа гробов по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />
   
}

<div>
    <article id="main" class="container special">
        <p>
            В магазине «Ритуал» на М.Горькго д.32 широкий ассортимент гробов лакированных,
            обшитых тканью и комбинированных.
        </p>
    </article>
    @if (Model.Any())
    {
        <section class="carousel">
            <div class="reel">

                @foreach (ServiceItem entity in Model)
                {
                    <article>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id"><img src="~/images/@entity.TitleImagePath" alt="" class="image1 featuredNew" /> </a>
                        <header>
                            <h3>@entity.Subtitle</h3>
                        </header>

                    </article>

                }
            </div>
        </section>
    }

</div>

Ritual/Ritual/Views/Services/Show.cshtml
@model Ritual.Domain.Entities.ServiceItem
@section metatags
{
    <title>Купить гроб в Глубоком</title>
    <meta name="description" content="Продажа гробов по доступным ценам в магазине «Ритуал» г.Глубокое, ул. М.Горького 32. Доставка в любой район. Работаем круглосуточно." />

}

<div>
    <article id="main" class="container special">
        <img class="image featured" src="~/images/@Model.TitleImagePath" />
        <h2>
            @Model.Title
        </h2>
    </article>
</div>